### ISSUE TITLE
[BUG] minio service version should be minio version, not chart version

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#1034]
```yaml

apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: minio
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: Minio is a High Performance Object Storage.
  serviceKind: minio
  serviceVersion: {{ .Chart.Version }}
```

`serviceVersion` is minio version, pls update.
