### ISSUE TITLE
[BUG] examples for mysql switchover ops should use custom ops instead

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#1042]
mysql use lorry to do switchover. offlload a custom ops instead.
```yaml
apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  ...
spec:
  clusterName: mysql-cluster
  custom:
    components:
    - componentName: mysql
      parameters:
      - name: candidate
        value: mysql-cluster-mysql-1
    opsDefinitionName: switchover
  ...
  type: Custom
```
