### ISSUE TITLE
[BUG] can't set Service "externalTrafficPolicy: Cluster"

### ISSUE THREAD

**Issue by shuoshadow** [apecloud/kubeblocks-addons#1071]
When I create a Service of type LoadBalancer, the value of externalTrafficPolicy is set to Local by default and cannot be changed to Cluster.
```yaml
apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: camellia-expose-enable
  namespace: kb-cloud
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: camellia-cluster
  # Lists Expose objects, each specifying a Component and its services to be exposed.
  expose:
    # Specifies the name of the Component.
  - componentName: proxy
    # Specifies a list of OpsService. When an OpsService is exposed, a corresponding ClusterService will be added to `cluster.spec.services`. 
    services:
    - name: internet
      roleSelector: ""
      serviceType: LoadBalancer
    # Indicates whether the services will be exposed. 'Enable' exposes the services. while 'Disable' removes the exposed Service.
    switch: Enable
  # Specifies the maximum number of seconds the OpsRequest will wait for its start conditions to be met before aborting. If set to 0 (default), the start conditions must be met immediately for the OpsRequest to proceed.
  preConditionDeadlineSeconds: 0
  type: Expose
```

![image](https://github.com/user-attachments/assets/04258afd-aa42-40f7-a7c2-1994a5d6d2f0)

  In my Kubernetes cluster, I’m using the Cilium CNI component and assigning EXTERNAL-IP to LoadBalancer type services through the CiliumBGPPeeringPolicy.
  When the Service has externalTrafficPolicy: Cluster, BGP Control Plane unconditionally advertises the ingress IPs of the selected Service. When the Service has externalTrafficPolicy: Local, BGP Control Plane keeps track of the endpoints for the service on the local node and stops advertisement when there’s no local endpoint.

https://docs.cilium.io/en/stable/network/bgp-control-plane/bgp-control-plane-v1/#externaltrafficpolicy

So I need to set the externalTrafficPolicy for the Service to Cluster.
