### ISSUE TITLE
[BUG] ElasticSearch remove the cluster.initial_master_nodes from node's configuration after the cluster has formed

### ISSUE THREAD

**Issue by iziang** [apecloud/kubeblocks-addons#1253]
**Describe the bug**

The Elasticseach reports the following error:

```plain
{"@timestamp":"2024-11-27T04:04:32.523Z", "log.level": "WARN", "message":"this node is locked into cluster UUID [CGVDtE9sQWSNrJSmdlm2hQ] but [cluster.initial_master_nodes] is set to [elastic2-mdit-0, elastic2-mdit-1, elastic2-mdit-2]; remove this setting to avoid possible data loss caused by subsequent cluster bootstrap attempts; for further information see https://www.elastic.co/guide/en/elasticsearch/reference/8.8/important-settings.html#initial_master_nodes", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"ES_ECS","process.thread.name":"main","log.logger":"org.elasticsearch.cluster.coordination.ClusterBootstrapService","elasticsearch.node.name":"elastic2-mdit-0","elasticsearch.cluster.name":"elastic2"}
```

elasticsearcy.yml
```yaml
cluster:
  name: elastic2
  routing:
    allocation:
      awareness:
        attributes: k8s_node_name
  initial_master_nodes:
  - elastic2-mdit-0
  - elastic2-mdit-1
  - elastic2-mdit-2

discovery:
# the default of discovery.type is multi-node, but can't set it to multi-node explicitly in 7.x version
  seed_hosts:
  - elastic2-mdit-0.elastic2-mdit-headless.default.svc.cluster.local
  - elastic2-mdit-1.elastic2-mdit-headless.default.svc.cluster.local
  - elastic2-mdit-2.elastic2-mdit-headless.default.svc.cluster.local

http:
  cors:
    enabled: true
    allow-origin: "*"
    allow-headers: Authorization,X-Requested-With,Content-Type,Content-Length
  publish_host: ${POD_FQDN}

network:
  host: "0"
  publish_host: ${POD_IP}

node:
  attr:
    k8s_node_name: ${NODE_NAME}
  name: ${POD_NAME}
  store:
    allow_mmap: false
# https://www.elastic.co/guide/en/elasticsearch/reference/7.7/modules-node.html
  roles:
  - master
  - data
  - ingest
  - transform

path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
