### ISSUE TITLE
[BUG] It is always in a horizontal scale state when upgrade

### ISSUE THREAD

**Issue by Shinnosukeys** [apecloud/kubeblocks-addons#1295]
**Describe the bug**
 It is always in a horizontal scale state when upgrade

**To Reproduce**
1.kbcli cluster create mycluster --cluster-definition mysql --set replicas=2 --topology-keys null -n demo
2.kubectl apply -f ops.yaml
![image](https://github.com/user-attachments/assets/ca9d7bb5-a03e-44e5-9ba2-13941774959a)
3.reslut
![image](https://github.com/user-attachments/assets/aa69d62f-02de-4833-8d05-772ecc866733)

**Expected behavior**
My cluster has completed the version upgrade

**Screenshots**

**Desktop (please complete the following information):**
mac
kb 0.9.2
kubernetes 1.20.11

**Additional context**

**Comment by shanshanying** [comment]
The ops you wrote incorrect:
```yaml
spec:
  clusterName: mycluster
  type: Upgrade
  upgrade:
    clusterVersionRef: mysql-8.4.2
```
