### ISSUE TITLE
[BUG] RabbitMQ using rabbitmqadmin to get list, shows only ONE replica.

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#1323]
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/11d51f63-addd-4a70-808c-9169c1e34263" />

```yaml
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: mycluster
  namespace: default
  labels:
    helm.sh/chart: rabbitmq-cluster-1.0.0-alpha.0
    app.kubernetes.io/version: "3.13.2"
    app.kubernetes.io/instance: mycluster
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: rabbitmq
      componentDef: rabbitmq
      serviceVersion: 3.13.7
      replicas: 3
      serviceAccountName:
      resources:
        limits:
          cpu: "0.5"
          memory: "0.5Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
      volumeClaimTemplates:
        - name: data # ref clusterDefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
````
