### ISSUE TITLE
[BUG] Long duration zookeeper health probe makes lots of 'defunct' child processes

### ISSUE THREAD

**Issue by nayutah** [apecloud/kubeblocks-addons#1397]
**Describe the bug**
When running a zookeeper cluster, the health probe operation may take more than 1 minute to complete and timeout. At the same time, the kb-agent may not 'waitpid' for the probe script properly, finally, the periodic probe scripts incurs lots of 'defunct' processes in the container.
I observe and trace the probe process in the container, find that in the process of health probe:
```
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          exec:
            command:
              - /bin/bash
              - -c
              - |
                . "$ZOOBINDIR"/zkEnv.sh > /dev/null
                java -cp "$CLASSPATH" $CLIENT_JVMFLAGS $JVMFLAGS org.apache.zookeeper.client.FourLetterWordMain \
                localhost 2181 ruok | grep imok
```
the jvm takes a very long time to do the JIT work 
```
288835 1001 20 0 2492424 47588 25044 R 0.3 0.3 0:00.19 C2 CompilerThread
```
when I use nc to replace 'java' cmd for health probe, the timeout and defunct problems disappear.
And this defection may occur frequently on VM with low-performance CPUs.
So I suggest using health probe cmd as belows:
```
            - bash
            - -c
            - |
              ZK_CLIENT_PORT=2181
              echo "ruok" | timeout 2 nc localhost ${ZK_CLIENT_PORT}; if [ $? -eq 0 ]; then echo "yes"; fi
```

**To Reproduce**
1. run a zookeeper cluster in GCP 4C16G vm
2. wait for the defunct processes to come out

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
