### ISSUE TITLE
[BUG] roleProbe fails with instance template

### ISSUE THREAD

**Issue by weicao** [apecloud/kubeblocks-addons#1440]
**Describe the bug**

Create a MySQL semi-sync cluster with 2 replicas (one Pod is created via a custom instance)

```yaml
kubectl apply -f - <<EOF
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: example-mysql-cluster-custom-pods
  namespace: demo
spec:
  clusterDef: mysql
  topology: server
  terminationPolicy: Delete
  componentSpecs:
    - name: mysql
      serviceVersion: 8.0.35
      replicas: 2
      resources:
        limits:
          cpu: '0.5'
          memory: 0.5Gi
        requests:
          cpu: '0.5'
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      instances:
        - name: custom
          replicas: 1
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
EOF
```

The Pods're created.
```bash
$ k get pods -n demo
NAME                                               READY   STATUS    RESTARTS   AGE
example-mysql-cluster-custom-pods-mysql-0          4/4     Running   0          118m
example-mysql-cluster-custom-pods-mysql-custom-0   4/4     Running   0          2m21s
```

However their roles're empty, and logs show:

2025-01-27 17:37:12.898 | 2025-01-27T09:37:12Z	INFO	DCS-K8S	k8s get cluster error	{"error": "json: cannot unmarshal object into Go struct field ClusterComponentSpec.spec.componentSpecs.instances of type string"} |  
-- | -- | --
  |   | 2025-01-27 17:37:12.899 | 2025-01-27T09:37:12Z	INFO	HTTPServer	operation exec failed	{"error": "get cluster failed: json: cannot unmarshal object into Go struct field ClusterComponentSpec.spec.componentSpecs.instances of type string"} |  
  |   | 2025-01-27 17:37:12.904 | 2025-01-27T09:37:12Z	INFO	send probe event	{"probe": "roleProbe", "probe": "roleProbe", "code": -1, "output": "primary", "message": "exit code: 1: failed"} |  
  |   | 2025-01-27 17:37:13.655 | 2025-01-27T09:37:13Z	INFO	DCS-K8S	k8s get cluster error	{"error": "json: cannot unmarshal object into Go struct field ClusterComponentSpec.spec.componentSpecs.instances of type string"} |  
  |   | 2025-01-27 17:37:13.655 | 2025-01-27T09:37:13Z	ERROR	HA	Get Cluster failed	{"error": "json: cannot unmarshal object into Go struct field ClusterComponentSpec.spec.componentSpecs.instances of type string"} |  
  |   | 2025-01-27 17:37:13.655 | github.com/apecloud/syncer/highavailability.(*Ha).RunCycle |  
  |   | 2025-01-27 17:37:13.655 | /src/highavailability/ha.go:89 |  
  |   | 2025-01-27 17:37:13.655 | github.com/apecloud/syncer/highavailability.(*Ha).Start |  
  |   | 2025-01-27 17:37:13.655 | /src/highavailability/ha.go:275

**Desktop (please complete the following information):**

KubeBlocks: 1.0.0-beta.23

kb-addon-mysql              	kb-system  	1       	2025-01-23 06:53:16.072199642 +0000 UTC	deployed	mysql-1.0.0-alpha.0         	5.7.44
