### ISSUE TITLE
[BUG] 多集群部署kubeblocks，报错 “dial tcp 192.168.76.2:8443: i/o timeout”

### ISSUE THREAD

**Issue by ZhaoHengJiang** [apecloud/kubeblocks-addons#1503]
**Describe the bug**
多集群部署kubeblocks，报错 “dial tcp 192.168.76.2:8443: i/o timeout”

**To Reproduce**
环境使用的官方开发镜像 docker.io/apecloud/kubeblocks-dev
用官方镜像搭建两个环境，并分别部署两个minikube，分别称为 az1 和 az2。
az1 作为控制面， az2作为数据面。
az1 的 config 为

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED # az2证书
    server: https://192.168.76.2:8443
  name: az2-data-cluster
contexts:
- context:
    cluster: az2-data-cluster
    user: control-client
  name: az1-control-az2-data
kind: Config
preferences: {}
users:
- name: control-client
  user:
    client-certificate-data: DATA+OMITTED # az1客户端证书
    client-key-data: DATA+OMITTED # az1客户端密钥
```

参考该文档 https://cn.kubeblocks.io/docs/preview/user-docs/maintenance/cross-k8s-deployment/ 多集群部署KB。
控制面 az1 参考 az1 的 config 准备 Config Secret

```
apiVersion: v1
kind: Secret
metadata:
  namespace: kb-system
  name: az1-az2
type: kubernetes.kubeconfig
stringData:
  kubeconfig: |
    kind: Config
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: DATA+OMITTED # az2证书
        server: https://192.168.76.2:8443
      name: az2-data-cluster
    contexts:
    - context:
        cluster: az2-data-cluster
        user: control-client
      name: az1-control-az2-data
    users:
    - name: control-client
      user:
        client-certificate-data: DATA+OMITTED # az1客户端证书
        client-key-data: DATA+OMITTED # az1客户端密钥
```

安装 KubeBlocks，并检查安装成功
`kbcli kubeblocks install --version=0.9.3 --set multiCluster.kubeConfig=az1-az2 --set multiCluster.contexts=az1-control-az2-data`

控制面 clusterrole 资源安装到数据面 az2
kubectl apply -f ~/kubeblocks-cluster-pod-role.yaml --context=az1-control-az2-data

查看 kubeblocks pods log，发现报错
2025-02-28T07:08:19.913Z	ERROR	controller-runtime.source.EventHandler	failed to get informer from cache	{"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get \"https://192.168.76.2:8443/api/v1\": dial tcp 192.168.76.2:8443: i/o timeout"}
2025-02-28T07:08:50.705Z	ERROR	controller-runtime.source.EventHandler	failed to get informer from cache	{"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: batch/v1: Get \"https://192.168.76.2:8443/apis/batch/v1\": dial tcp 192.168.76.2:8443: i/o timeout"}

**Expected behavior**
KB跨集群部署成功

**Desktop (please complete the following information):**
官方镜像 docker.io/apecloud/kubeblocks-dev

**Comment by shanshanying** [comment]
Please check network connectivity as requireted in the doc:
> Make sure the API servers of these data plane K8s clusters can be reached from the control plane, which should include both network connectivity and access configuration.

Can the POD in az1 visits the API Server of AZ2? I mean from a POD in az1, not minikube node.

**Comment by ZhaoHengJiang** [comment]
我创建了一个专门用来测试的curl pod，
并将控制面证书、密钥和数据面证书依次拷贝到 ~/client.crt 、~/client.key 和 ~/ca.crt 。
执行 curl 访问数据面 apiserver 成功
```
~ $ curl https://192.168.76.2:8443 \
>   --cert ~/client.crt \
>   --key ~/client.key \
>   --cacert ~/ca.crt
{
  "paths": [
    "/.well-known/openid-configuration",
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apps",
    "/apis/apps/v1",
    ...
```

**Comment by shanshanying** [comment]
here is a simple test 
1.  in K8s`az1`, create a pod, mount your  config secret `az1-az2`mimc what KubeBlocks does.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-conn
  namespace: kb-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 10000
    image: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-tools:0.9.3
    imagePullPolicy: IfNotPresent
    name: test-conn
    resources: {}
    volumeMounts:
    - mountPath: /var/run/secrets/kubeblocks.io/multicluster
      name: multi-cluster-kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  volumes:
  - name: multi-cluster-kubeconfig
    secret:
      defaultMode: 420
      secretName: az1-az2  # use your multi-k8s-cluster secret
```
2. exet into the pod and check connection 
```bash 
 k -n kb-system exec -it test-conn -- /bin/sh
```
and check connectivity from the pod
```bash
# execute the command within pod test-conn
kubectl get pod --kubeconfig /var/run/secrets/kubeblocks.io/multicluster/kubeconfig
```
