### ISSUE TITLE
[Features] Milvus supports external etcd and Pulsar configurations

### ISSUE THREAD

**Issue by groobyming** [apecloud/kubeblocks-addons#1558]
Currently, the cluster installation method of Milvus-addon requires you to build your own etcd and Pulsar first. If I already have etcd and Pulsar services in the cloud, how should I configure these external services?

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/e382f59e-3ff7-49c6-b8ec-ac4927bd2c91" />

**Comment by shanshanying** [comment]
Hi @groobyming 

Here is an example from Kafka using external Zookeeper. https://github.com/apecloud/kubeblocks-addons/blob/release-1.0-beta/examples/kafka/cluster-2x-ext-zk-svc-descriptor.yaml


1. You may create a `ServiceDescriptor` CR for your external ETCD

```yaml
apiVersion: apps.kubeblocks.io/v1
kind: ServiceDescriptor
metadata:
  name: kafka-cluster-zookeeper-service
  namespace: default
spec:
  # Specifies the type or nature of the service.
  # Should represent a well-known application cluster type, such as {mysql, redis, zookeeper}.
  serviceKind: zookeeper
  # Represents the version of the service reference.
  serviceVersion: 3.8.5
  # Represents the endpoint of the service connection credential.
  endpoint:
    # your external zk endpoints here
    value: "zookeeper-cluster-zookeeper-0.zookeeper-cluster-zookeeper-headless.default:2181,zookeeper-cluster-zookeeper-1.zookeeper-cluster-zookeeper-headless.default:2181,zookeeper-cluster-zookeeper-2.zookeeper-cluster-zookeeper-headless.default:2181"
  # Represents the port of the service connection credential.
  port:
    value: "2181"
```

2. Use this ServiceDescriptor in Cluster's `serviceRef` API
```yaml
  componentSpecs:
    - name: kafka-broker
      componentDef: kafka27-broker
      serviceRefs:
        - name: kafkaZookeeper
          namespace: default
          serviceDescriptor: kafka-cluster-zookeeper-service
```

**Comment by groobyming** [comment]
Another question is, if I want to set the connection information of an external Pulsar, how should I set it? For example, if I use the official Helm chart of Milvus, I can set the values as follows.

<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/78760c97-a999-4ac9-aaef-2f7af5bf8e5a" />

**Comment by shanshanying** [comment]
Hi @groobyming 

I checked the configuration of Milvus Addon, and found in : https://github.com/apecloud/kubeblocks-addons/blob/7ff48016b00a6d0bcc37a4da6f706dad3a4be6ce/addons/milvus/configs/cluster-user.yaml#L1
```yaml
etcd:
  endpoints:
    - {{ .ETCD_ENDPOINT }}
  rootPath: {{ .CLUSTER_NAME }}
messageQueue: pulsar
minio:
  address: {{ .MINIO_SERVER }}
  port: {{ .MINIO_PORT }}
  accessKeyID: MINIO_ACCESS_KEY
  secretAccessKey: MINIO_SECRET_KEY
  bucketName: {{ .CLUSTER_NAME }}
mq:
  type: pulsar
msgChannel:
  chanNamePrefix:
    cluster: {{ .CLUSTER_NAME }}
pulsar:
  address: {{ .PULSAR_SERVER }}
  port: {{ .PULSAR_PORT }}
```

As it shows, Milvus does not config any AUTH info to connect Pulsar.
We will check if there is a way to improve it.
