### ISSUE TITLE
[BUG] update ZK volumeMounts

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#1581]
```yaml
        volumeMounts:
          - name: data
            mountPath: /bitnami/zookeeper/data
          - name: snapshot-log
            mountPath: /bitnami/zookeeper/log
          - name: log
            mountPath: /opt/bitnami/zookeeper/logs
          - name: config
            mountPath: /opt/bitnami/zookeeper/conf/zoo.cfg
            subPath: zoo.cfg
          - name: config-log
            mountPath: /opt/bitnami/zookeeper/conf/logback.xml
            subPath: logback.xml
          - name: config-log
            mountPath: /opt/bitnami/zookeeper/conf/log4j.properties
            subPath: log4j.properties
          - name: scripts
            mountPath: /kubeblocks/scripts
```

Check which config-log to use
