### ISSUE TITLE
[BUG]The matchNames field should be set to demo since all clusters in the example are created in demo namespace

### ISSUE THREAD

**Issue by tianyue86** [apecloud/kubeblocks-addons#1634]
**Describe the bug**
```
Kubernetes: v1.31.1-aliyun.1
KubeBlocks: 1.0.0-beta.44
kbcli: 1.0.0-beta.20
```

**To Reproduce**
1. The matchNames field should be set to demo since all clusters in the example are created in the demo namespace
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mysql-cluster-pod-monitor
  labels:               # this is labels set in `prometheus.spec.podMonitorSelector`
    release: prometheus
spec:
  jobLabel: app.kubernetes.io/managed-by
  # defines the labels which are transferred from the
  # associated Kubernetes `Pod` object onto the ingested metrics
  # set the lables w.r.t you own needs
  podTargetLabels:
  - app.kubernetes.io/instance
  - app.kubernetes.io/managed-by
  - apps.kubeblocks.io/component-name
  - apps.kubeblocks.io/pod-name
  podMetricsEndpoints:
    - path: /metrics
      port: http-metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql-cluster
      apps.kubeblocks.io/component-name: mysql
```
3. Click on '....'
4. Scroll down to '....'
5. See error
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
