### ISSUE TITLE
[BUG] ElasticSearch does not check auth info.

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#1655]
1. kb version: 0.9.3
2.  create es, user can access data without username/password

```yaml
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: es-no-tls
  namespace: default
  annotations:
    kubeblocks.io/extra-env: '{"master-roles":"master", "dit-roles":"data,ingest,transform","mode":"multi-node"}'
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: master
      componentDef: elasticsearch-8
      serviceVersion: 8.8.2
      serviceAccountName: kb-elsearch-cluster
      replicas: 1
      disableExporter: false
      resources:
        limits:
          cpu: '0.5'
          memory: 2Gi
        requests:
          cpu: '0.5'
          memory: 2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
    - name: dit
      componentDef: elasticsearch-8
      serviceVersion: 8.8.2
      serviceAccountName: kb-elsearch-cluster
      replicas: 3
      disableExporter: false
      resources:
        limits:
          cpu: '0.5'
          memory: 2Gi
        requests:
          cpu: '0.5'
          memory: 2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
```

3. login to any es replica and query data:

the username and password given are invlaid. But there is no check
```bash
 curl -X GET "http://localhost:9200/_search?pretty"  -u abcd:xyz
```
