### ISSUE TITLE
[BUG] ElasticSearch with TLS enabled, failed to create the cluster.

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#1656]
1. kb version: 0.9.3
2. create es cluster with tls enabled, `es-tls-secret` is the secret with user defined cert info.
```yaml
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: es-with-tls
  namespace: default
  annotations:
    kubeblocks.io/extra-env: '{"master-roles":"master", "dit-roles":"data,ingest,transform","mode":"multi-node"}'
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: master
      componentDef: elasticsearch-8
      serviceVersion: 8.8.2
      serviceAccountName: kb-elsearch-cluster
      replicas: 1
      tls: true
      issuer:
        name: UserProvided
        secretRef:
          name: es-tls-secret
          ca: ca.crt
          cert: tls.crt
          key: tls.key
      disableExporter: false
      resources:
        limits:
          cpu: '0.5'
          memory: 2Gi
        requests:
          cpu: '0.5'
          memory: 2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
    - name: dit
      componentDef: elasticsearch-8
      serviceVersion: 8.8.2
      serviceAccountName: kb-elsearch-cluster
      replicas: 3
      tls: true
      issuer:
        name: UserProvided
        secretRef:
          name: es-tls-secret
          ca: ca.crt
          cert: tls.crt
          key: tls.key
      disableExporter: false
      resources:
        limits:
          cpu: '0.5'
          memory: 2Gi
        requests:
          cpu: '0.5'
          memory: 2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
```

4. master component started successfully.
5. dit componet stucks in creating with error
```bash
k get po
NAME                   READY   STATUS            RESTARTS   AGE
es-with-tls-dit-0      0/3     PodInitializing   0          4m24s
es-with-tls-dit-1      2/3     Running           0          4m24s
es-with-tls-dit-2      2/3     Running           0          4m24s
es-with-tls-master-0   3/3     Running           0          4m24s
```
to get logs:
```bash
 k logs es-with-tls-dit-1

{"@timestamp":"2025-05-06T08:32:50.700Z", "log.level": "INFO", "message":"Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"ES_ECS","process.thread.name":"elasticsearch[es-with-tls-dit-1][transport_worker][T#1]","log.logger":"org.elasticsearch.xpack.security.authc.RealmsAuthenticator","elasticsearch.cluster.uuid":"1Rdi53-JSEmCQWErm9j53Q","elasticsearch.node.id":"W1pcIyUfRhqsQULrMj6FSw","elasticsearch.node.name":"es-with-tls-dit-1","elasticsearch.cluster.name":"es-with-tls"}
{"timestamp": "2025-05-06T08:32:50+00:00", "message": "readiness probe failed",  "status": "401"}
```
