### ISSUE TITLE
[BUG] PostgreSQL AddOn: Secondary Instance Fails to Apply `max_connections` Reduction, Remains Pending Restart​

### ISSUE THREAD

**Issue by dingshun-cmss** [apecloud/kubeblocks-addons#1691]
## Describe the bug
When modifying the `max_connections` parameter in a PostgreSQL cluster using the PostgreSQL AddOn, **only the primary instance restarts** with the updated value, while **the secondary instance remains pending for restart** and retains the previous value.

## To Reproduce
1. Create a PostgreSQL cluster using the PostgreSQL AddOn.
2. Create an `OpsRequest` to modify `max_connections` to a smaller value. Example:
```yaml
apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  generateName: dstest-reconfig-
  namespace: dbaas
spec:
  clusterRef: dstestpg
  reconfigure:
    componentName: postgresql
    configurations:
    - keys:
      - key: postgresql.conf
        parameters:
        - key: max_connections
          value: "50"
      name: postgresql-configuration
  type: Reconfiguring
```
3. Apply the `OpsRequest` and verify the `max_connections` value on both primary and secondary instances.
4. Observe that:
    - The primary reflects the new value (50).
    - The secondary remains pending for restart and retains the old value.

## Expected behavior
Both the primary and secondary instances should restart and apply the new `max_connections` value simultaneously.

## Information
- KubeBlocks version: 0.9.3

## Additional context
When increasing `max_connections`, both instances restart as expected. The issue only occurs when decreasing the value.
