### ISSUE TITLE
[Improvement]  kafka-addon support configure kerberos keytab file for each instance

### ISSUE THREAD

**Issue by CharlesQQ** [apecloud/kubeblocks-addons#1738]
Is your improvement request related to a problem? Please describe.

For now, we have a kafka cluster that needs to be containerized using kubeblocks; each kafka broker node is configured with a kerberos keytab file for security, and the keytab file is associated with the host name (instance name); we hope that the kafka addons can support the requirement to configure a keytab file for each instance

If this is a new function, please describe the motivation and goals.
A clear and concise description of why you want to happen, link the design doc if possible

The keytab file can be obtained through a remote interface (eg: http interface) containing a host name parameter. The keytab of each instance is different.

Describe the solution you'd like

Describe alternatives you've considered
A clear and concise description of any alternative solutions or functions you've considered.

The keytab should be stored in a secret and mounted to a fixed directory in the pod using volumemount

Additional context
Add any other context or screenshots about the improvement request here.

**Comment by shanshanying** [comment]
Hi @CharlesQQ 

after some discussion, we found one feasible way is:

Suppose you have generated a secret , containing keytabfile for all instances.

1. update ComponentDefintion to add an extra `volumeMounts` for keytabfile
e.g.
```yaml
# componentdefinition.yaml
volumeMounts:
  - name: keytabfile
    mountPath: /path/to/keytabfile
```

2. update start up script, parsing for each pod the crossponding keytable file mounted to '/path/to-keytabfile' and save it to `/opt/.security/kafka.keytab`

3. generate the secret for keytab files

4. create a cluster and specifying `volumes` info:
```yaml
# cluster.yaml
    volumes:
      - name: keytabfile  # must match the name in step 1.
        secret:
          secretName: secret-generated-at-step-3
```


Hope this will help.
