### ISSUE TITLE
Reconfigure on Redis doesn't work for client-output-buffer-limit

### ISSUE THREAD

**Issue by yogeshcbsi** [apecloud/kubeblocks-addons#1758]
Reconfigure `OpsRequest` on Redis Cluster fails with below example for `client-output-buffer-limit` parameters.

KubeBlocks & Redis Add-on Version: `1.0.0`

```
apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: demo-cache-reconfigure-static-ops
  namespace: demo
spec:
  clusterName: demo-cache
  ttlSecondsAfterSucceed: 60
  reconfigures:
    - componentName: shard
      parameters:
        - key: client-output-buffer-limit-pubsub-soft-limit
          value: "8388608"
  type: Reconfiguring
```

Also tried with below request but that doesn't trigger any change.

```
apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: demo-cache-reconfigure-static-ops
  namespace: demo
spec:
  clusterName: demo-cache
  ttlSecondsAfterSucceed: 60
  reconfigures:
    - componentName: shard
      parameters:
        - key: client-output-buffer-limit
          value: "pubsub 33554432 8388608 60"
  type: Reconfiguring
```
