### ISSUE TITLE
[BUG] zookeeper cluster list-logs No such file or directory

### ISSUE THREAD

**Issue by JashBook** [apecloud/kubeblocks-addons#227]
**Describe the bug**

**To Reproduce**
1. create cluster 
```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: zkeeper-pfkpxz
  namespace: default
spec:
  clusterDefinitionRef: zookeeper
  clusterVersionRef: zookeeper-3.7.2
  terminationPolicy: WipeOut
  componentSpecs:
    - name: zookeeper
      componentDefRef: zookeeper
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 0.5Gi
        limits:
          cpu: 100m
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - name: data-log
          spec:
            storageClassName:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
```
2. See error
```
kbcli cluster list-logs zkeeper-pfkpxz
ls: cannot access '/opt/zookeeper/logs/zookeeper_audit.log': No such file or directory
ls: cannot access '/opt/zookeeper/logs/zookeeper-*-server-*.log': No such file or directory
ls: cannot access '/opt/zookeeper/logs/zookeeper_audit.log': No such file or directory
ls: cannot access '/opt/zookeeper/logs/zookeeper-*-server-*.log': No such file or directory
ls: cannot access '/opt/zookeeper/logs/zookeeper_audit.log': No such file or directory
ls: cannot access '/opt/zookeeper/logs/zookeeper-*-server-*.log': No such file or directory
No log files found. You can enable the log feature with the kbcli command below.
kbcli cluster update zkeeper-pfkpxz --enable-all-logs=true --namespace default
```

**Expected behavior**
zookeeper cluster list-logs success.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
