### ISSUE TITLE
[Improvement] cluster component has roles, clsuter expose at least one of 'roleSelector' or 'podSelector' must be specified

### ISSUE THREAD

**Issue by JashBook** [apecloud/kubeblocks-addons#763]
Is your improvement request related to a problem? Please describe.
cluster component has roles, clsuter expose at least one of 'roleSelector' or 'podSelector' must be specified

If this is a new function, please describe the motivation and goals.
cluster component has roles, at least one of 'roleSelector' or 'podSelector' must be specified

Describe the solution you'd like
```
kbcli cluster expose scale-pecanq --auto-approve --force=true                  --type vpc --enable true                 --components mysql  --dry-run
apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  generateName: scale-pecanq-expose-
  labels:
    app.kubernetes.io/instance: scale-pecanq
    app.kubernetes.io/managed-by: kubeblocks
  namespace: default
spec:
  clusterName: scale-pecanq
  expose:
  - componentName: mysql
    services:
    - annotations:
        networking.gke.io/load-balancer-type: Internal
      name: vpc
      roleSelector: leader
      serviceType: LoadBalancer
    switch: Enable
  force: true
  ttlSecondsAfterSucceed: 0
  type: Expose
```

Describe alternatives you've considered
A clear and concise description of any alternative solutions or functions you've considered.

Additional context
