### ISSUE TITLE
[Improvement] ElasticSearch should add `exporter` in cmpd

### ISSUE THREAD

**Issue by weicao** [apecloud/kubeblocks-addons#804]
Otherwise, when `disableExporter` is set to false, the exporter won't be scrapped by the Prometheus installed by kb-addon-prometheus.

```
apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
  name: elasticsearch-7.7

...

  exporter:
    containerName: exporter
    scrapePath: /metrics
    scrapePort: metrics
```
