### ISSUE TITLE
[BUG] PITR Not Work for PostgreSQL AddOn

### ISSUE THREAD

**Issue by dingshun-cmss** [apecloud/kubeblocks-addons#967]
**Describe the bug**
The PITR feature for PG doesn't work

**To Reproduce**
1. Prepare for the full backup and WAL archive for the source DB
2. Create an `OpsRequest` , with some contents like this:
```yaml
apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  generateName: dstestrestore-
spec:
  clusterRef: dstestpg-restore2
  restoreSpec:
    backupName: backup-dbaas-dstestpg-20240821073913
    volumeRestorePolicy: Parallel
    restoreTimeStr: "2024-08-21T07:44:20Z"
  ttlSecondsAfterSucceed: 30
  ttlSecondsBeforeAbort: 0
  type: Restore
```

The restored DB cannot start successfully.  

When we check the logs for the failed DB contaier, we can find the following line:
```
2024-08-21 07:49:37 GMT [93]: [1-1] 66c59c11.5d 0     LOG:  invalid value for parameter "recovery_target_time": "2024-08-21T07:44:20Z"
```

Here's the restore part in the generated patroni config:
```
  ...
  kb_restore_from_time:
    command: bash /home/postgres/pgdata/kb_restore/kb_restore.sh
    keep_existing_recovery_conf: false
    recovery_conf:
      recovery_target_action: promote
      recovery_target_time: '2024-08-21T07:44:20Z'
      recovery_target_timeline: latest
      restore_command: envdir /home/postgres/pgdata/wal-g/restore-env /home/postgres/pgdata/wal-g/wal-g
        wal-fetch %f %p >> /home/postgres/pgdata/kb_restore/wal-g.log 2>&1
  ...
```

It looks like that PostgreSQL doesn't recognize the RFC-3339 format for restore timestamp.

Then I tried to change the `restoreTimeStr` to a format that is recognized by PostgreSQL: `2024-08-21 07:44:20+00` ,  and recreate the `OpsRequest` .  However, the Pods cannot be created.  There're some errors in the KB operator log: 
```
2024-08-21T08:17:54.173Z    ERROR    Reconciler error    {"controller": "component", "controllerGroup": "apps.kubeblocks.io", "controllerKind": "Component", "Component": {"name":"dstestpg-restore2-postgresql","namespace":"dbaas"}, "namespace": "dbaas", "name": "dstestpg-restore2-postgresql", "reconcileID": "b73f9e1d-e16d-447d-8686-46c6b0831db1", "error": "Restore.dataprotection.kubeblocks.io \"dstestpg-restore2-postgresql-12170f54-preparedata\" is invalid: spec.restoreTime: Invalid value: \"2024-08-21 07:44:20+00\": spec.restoreTime in body should match '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$'"}
```

**Expected behavior**
The OpsRequest restore should finish without problems, for RFC-3339 timestamp format.  

**Screenshots**
N/A

**Additional Context**
PG version is PG 14
